import { useEffect } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  useEffect(() => {
    const stored = localStorage.getItem("theme");
    if (stored === "dark") {
      document.documentElement.classList.add("dark");
    }
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-black dark:bg-gray-900 dark:text-white transition-colors`}
      >
        <button
          onClick={() => {
            const html = document.documentElement;
            const isDark = html.classList.contains("dark");
            if (isDark) {
              html.classList.remove("dark");
              localStorage.setItem("theme", "light");
            } else {
              html.classList.add("dark");
              localStorage.setItem("theme", "dark");
            }
          }}
          className="fixed top-4 right-4 z-50 px-3 py-1 text-sm rounded bg-black text-white dark:bg-white dark:text-black shadow"
        >
          Toggle Theme
        </button>
        {children}
      </body>
    </html>
  );
}
